version: '3.9'

services:
# database
  database:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password

# backend
  backend:
    container_name: backend
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_USERNAME=username
      - DB_PASSWORD=password